@startuml
class User {
    firstName: String
    lastName: String
    email: String
    password: String
    type: String
    state: String
}

class Event {
   ID : Integer
   Name : String
   Desc : String
   startDate: Date
   startTime: Date
   endDate: Date
   endTime: Date
   creator: String
   joined []: User
   waiting []: User
   feedbacks[]: Feedback
}

class Feedback {
   by: User
   text : String
   Reply : String
}

User "1" - "*" Event : creates
User "*" - "*" Event : joins
User "1" - "*" Feedback : sends
Event "*" *- "*" Feedback
@enduml
